const profileService = require('../../services/seekers/profile');

const getProfile = async (req, res,next) => {
    try {
        const userId = req.user.id;
        let profile = await profileService.getProfile(userId);
        res.status(200).json({ success: true, data: profile });
    } catch (error) {
        res.status(404).json({ success: false, message: error.message });
    }
};

const updateAvatar = async (req, res, next) => {
    try {
        const userId = req.user.id; // From JWT token (matches `Id` in tbl_users)

        // Check if file was uploaded
        if (!req.file) {
            return res.status(400).json({
                success: false,
                message: 'Please select an image file'
            });
        }

        // Get the new filename generated by Multer
        const avatarFileName = req.file.filename; // e.g., "1699999999999-123456789.jpg"

        // Call Service to update database
        const result = await profileService.updateAvatar(userId, avatarFileName);

        res.status(200).json({
            success: true,
            message: result.message,
            data: { avatar: avatarFileName }
        });
    } catch (error) {
        next(error);
    }
};

const updateProfile = async (req, res) => {
    try {
        // Make sure req.user is set by auth middleware
        if (!req.user || !req.user.id) {
            return res.status(401).json({ 
                success: false, 
                message: 'Unauthorized – user not found' 
            });
        }

        const userId = req.user.id;
        const body = req.body;
        const file = req.file;

        // Call the service function (not itself) via the alias
        const result = await profileService.updateProfile(userId, body, file);

        res.status(200).json({
            success: true,
            message: result.message
        });
    } catch (error) {
        console.error('Profile update error:', error);
        res.status(400).json({ 
            success: false, 
            message: error.message 
        });
    }
};

// create Experience
const createExperience = async (req, res, next) => {
    try {
        const userId = req.user.id; // ពី Token
        const result = await profileService.createExperience(userId, req.body);
        res.status(201).json({
            success: true,
            message: result.message,
            experienceId: result.experienceId
        });
    } catch (error) {
        console.error('Error creating experience:', error);
        next(error);
    }
};


module.exports = {
    getProfile,
    updateAvatar,
    updateProfile,
    createExperience
};