const profileService = require('../../services/seekers/profile');

const getProfile = async (req, res,next) => {
    try {
        const userId = req.user.id;
        let profile = await profileService.getProfile(userId);
        res.status(200).json({ success: true, data: profile });
    } catch (error) {
        res.status(404).json({ success: false, message: error.message });
    }
};

const updateAvatar = async (req, res, next) => {
    try {
        const userId = req.user.id; // From JWT token (matches `Id` in tbl_users)

        // Check if file was uploaded
        if (!req.file) {
            return res.status(400).json({
                success: false,
                message: 'Please select an image file'
            });
        }

        // Get the new filename generated by Multer
        const avatarFileName = req.file.filename; // e.g., "1699999999999-123456789.jpg"

        // Call Service to update database
        const result = await profileService.updateAvatar(userId, avatarFileName);

        res.status(200).json({
            success: true,
            message: result.message,
            data: { avatar: avatarFileName }
        });
    } catch (error) {
        next(error);
    }
};

const updateProfile = async (req, res) => {
    try {
        const id = req.user.id; // ឬ req.params.id

        const response = await profileService.updateProfile(id, req.body);

        if (!response.result) {
            return res.status(400).json(response);
        }

        return res.status(200).json(response);
    } catch (error) {
        console.error(error);

        return res.status(500).json({
            result: false,
            msg: "Internal Server Error"
        });
    }
};


// create Experience
const createExperience = async (req, res, next) => {
    try {
        const userId = req.user.id; // ពី Token
        const result = await profileService.createExperience(userId, req.body);
        res.status(201).json({
            success: true,
            message: result.message,
            experienceId: result.experienceId
        });
    } catch (error) {
        console.error('Error creating experience:', error);
        next(error);
    }
};

const uploadCv = async (req, res, next) => {
    try {
        const userId = req.user.id;
        const { filename } = req.body; // or from multer: req.file.filename
        if (!filename) {
            return res.status(400).json({ success: false, message: 'Filename is required' });
        }
        const result = await profileService.uploadCv(userId, filename);
        res.status(201).json({ success: true, message: result.message, cvId: result.cvId });
    } catch (error) {
        next(error);
    }
};

const updateSkill = async (req, res, next) => {
    try {
        const userId = req.user.id;
        const { skill } = req.body;
        if (!skill) {
            return res.status(400).json({ success: false, message: 'Skill is required' });
        }
        const result = await profileService.updateSkill(userId, skill);
        res.status(200).json({ success: true, message: result.message });
    } catch (error) {
        next(error);
    }
};

const updateExperience = async (req, res, next) => {
    try {
        const experienceId = req.params.id;
        const result = await profileService.updateExperience(experienceId, req.body);
        res.status(200).json({ success: true, message: result.message });
    } catch (error) {
        next(error);
    }
};

module.exports = {
    getProfile,
    updateAvatar,
    updateProfile,
    uploadCv,
    updateSkill,
    updateExperience,
    createExperience
};